export type ProjectCategory = "Интерьеры" | "Архитектура" | "Ландшафт";
export type FilterCategory = ProjectCategory | "Все";

export type Project = {
  id: number;
  slug: string;
  title: string;
  category: ProjectCategory;
  location: string;
  year: string;
  filterSquare?: string | null;
  filterTone?: string | null;
  description: string;
  image: string;
  heroImages?: string[];
  beforeImage?: string;
  afterImage?: string;
  caseIntro?: string;
  galleryEyebrow?: string;
  galleryTitle?: string;
  galleryText?: string;
  galleryImages?: string[];
  galleryLabels?: string[];
  isFeatured?: boolean;
  isSelected?: boolean;
  isVirtualTour?: boolean;
  virtualTour?: {
    eyebrow?: string | null;
    eyebrowRu?: string | null;
    eyebrowEn?: string | null;
    title?: string | null;
    titleRu?: string | null;
    titleEn?: string | null;
    text?: string | null;
    textRu?: string | null;
    textEn?: string | null;
    buttonLabel?: string | null;
    buttonLabelRu?: string | null;
    buttonLabelEn?: string | null;
    scenes?: {
      id: string;
      title?: string | null;
      titleRu?: string | null;
      titleEn?: string | null;
      label?: string | null;
      panorama: string;
      yaw?: number;
      pitch?: number;
      plan?: { x: number; y: number; width?: number; height?: number };
      next?: {
        id: string;
        text?: string | null;
        textRu?: string | null;
        textEn?: string | null;
        yaw?: number;
        pitch?: number;
        targetYaw?: number | null;
      }[];
    }[];
  };
  selectedCards?: {
    title?: string;
    titleRu?: string;
    titleEn?: string;
    text?: string;
    textRu?: string;
    textEn?: string;
  }[];
  featuredLabel?: string;
  featuredTitle?: string;
  featuredDescription?: string;
  featuredImage?: string;
  featuredGalleryImages?: string[];
  storyChapters?: {
    title?: string;
    titleRu?: string;
    titleEn?: string;
    title_ru?: string;
    title_en?: string;
    text?: string;
    textRu?: string;
    textEn?: string;
    text_ru?: string;
    text_en?: string;
  }[];
  deliverables?: string[];
};
